docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Intro: intro.md
    - Reflection: reflection.md
site_name: zend-server
site_description: zend-server
repo_url: 'https://github.com/zendframework/zend-server'
copyright: 'Copyright (c) 2005-2018 <a href="https://www.zend.com/">Zend Technologies USA Inc.</a>'

